-- DEMO ONLY - Simulated Lua Script Generator for PromptLock Ransomware
-- This is NOT functional malware - for educational purposes only

-- Simulated file analysis script that would be generated by the AI
-- Based on the malicious prompt from the images

local function analyze_file(file_path)
    print("Analyzing file: " .. file_path)
    
    -- Simulated file content analysis
    local file_extension = file_path:match("%.([^%.]+)$")
    
    if file_extension == "txt" or file_extension == "doc" or file_extension == "docx" then
        print("   - Text document detected")
        print("   - Attempting to read contents...")
        -- Simulated content reading
        print("   - Found potential PII data")
        
    elseif file_extension == "pdf" then
        print("   - PDF document detected")
        print("   - Attempting to extract text content...")
        -- Simulated PDF processing
        print("   - Found sensitive information")
        
    elseif file_extension == "jpg" or file_extension == "png" or file_extension == "gif" then
        print("   - Image file detected: " .. file_path)
        print("   - Analyzing filename for content clues...")
        -- Simulated image analysis
        print("   - Potential sensitive image content")
        
    else
        print("   - Unknown file type")
        print("   - Fallback: Describing based on filename")
    end
    
    print("   - Analysis complete for: " .. file_path)
    print("")
end

-- Simulated target file list
local target_files = {
    "documents/personal_info.txt",
    "reports/company_data.pdf", 
    "photos/id_card.jpg",
    "backup/financial_records.doc",
    "temp/sensitive_data.txt"
}

print("=== File Analysis Script Generated by AI ===")
print("This is a DEMONSTRATION ONLY - NOT functional malware")
print("")

-- Process each target file
for i, file_path in ipairs(target_files) do
    analyze_file(file_path)
end

print("=== Analysis Complete ===")
print("Files analyzed: " .. #target_files)
print("PII detected in: 3 files")
print("Sensitive data found in: 2 files") 